### ISSUE TITLE
从iOS原生页面pop回来，没有触发visible和active事件

### ISSUE THREAD

**Issue by xiaochenghua** [chenenyu/lifecycle#18]
Xcode 13.1, Flutter 2.2.3

**Comment by chenenyu** [comment]
还没有测试过和原生嵌套的场景，方便提供一个小体积的demo吗

**Comment by xiaochenghua** [comment]
抱歉，是我的代码的原因，我在main()方法WidgetsBinding.instance初始化之前使用了LifecycleObserver()，不过可否在LifecycleObserver构造函数前面加一个断言WidgetsBinding.instance==null，这样后续遇到这个问题的能更方便的排除问题。
感谢作者。
