### ISSUE TITLE
Windows/Linux support

### ISSUE THREAD

**Issue by ollydixon** [chenenyu/lifecycle#21]
It's not clear if this package supports Windows or Linux as I don't see any code for it?

**Comment by chenenyu** [comment]
This is a pure flutter package library, so it doesn't need any c++ code to support windows/linux, could you please have a try and give me a feedback? 😄

**Comment by ollydixon** [comment]
@chenenyu on pub.dev you've listed that it covers all platforms. At the moment it looks like there's no library that does all. If you could make that happen it would be amazing!

**Comment by chenenyu** [comment]
@ollydixon I mean that this library already supports windows or linux now. You can try it and tell me if there are any bugs in it.

**Comment by ollydixon** [comment]
@chenenyu it won't work if there's no native plugins written

**Comment by chenenyu** [comment]
There's also no native plugins for Android and iOS, but it works on those platforms.

**Comment by ollydixon** [comment]
<img width="569" alt="Screenshot 2022-05-01 at 16 03 01" src="https://user-images.githubusercontent.com/6940726/166149326-c7fd6301-b424-4236-8632-ec1cda145ef1.png">

**Comment by ollydixon** [comment]
As you can see it says "Linux, MacOS, Web and Windows support" :-) perhaps you should remove that.
