### ISSUE TITLE
在使用popUntil关闭多个窗口后退时，被关闭的窗口在pop事件之前，会多触发一次visible和active事件

### ISSUE THREAD

**Issue by yeswah** [chenenyu/lifecycle#9]
使用的是最新版 lifecycle: ^0.3.2

`Navigator.of(context).popUntil((route) => route.settings.name == "home");`

flutter: Page3 LifecycleEvent.inactive
flutter: Page3 LifecycleEvent.invisible
flutter: Page2 LifecycleEvent.visible
flutter: Page2 LifecycleEvent.active
flutter: Page2 LifecycleEvent.inactive
flutter: Page2 LifecycleEvent.invisible
flutter: Page1 LifecycleEvent.visible
flutter: Page1 LifecycleEvent.active
flutter: Page1 LifecycleEvent.inactive
flutter: Page1 LifecycleEvent.invisible
flutter: Page3 LifecycleEvent.visible
flutter: Page3 LifecycleEvent.active
flutter: Page2 LifecycleEvent.visible
flutter: Page2 LifecycleEvent.active
flutter: Page3 LifecycleEvent.pop
flutter: Page2 LifecycleEvent.pop
flutter: Page1 LifecycleEvent.pop

**Comment by chenenyu** [comment]
好的，我先看下。

**Comment by chenenyu** [comment]
还有问题吗？

**Comment by yeswah** [comment]
已经用上了，没问题，谢谢及时处理
